version: '3.4' 

services:
  webapi:
    container_name: c_webapi
    image: webapi 
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8099:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  s_portal:
    container_name: c_portal
    image: portal_image
    restart: always
    build:
      context: .
      args:
      - VUE_APP_API_URL=https://apitest.nilvera.com
      dockerfile: VuejsApp/Dockerfile
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=development